### ISSUE TITLE
出现了很多的bug求解

### ISSUE THREAD

**Issue by jiaoziqun** [The-Alchemist-0517/demo-3.3-strategy#1]
运行这个代码的gym和pyglet的版本是多少?我是用的在github上下载的一个带rendering的gym，现在的版本都不带rendering了，然后pyglet版本是1.2.4.python是3.7，但是出现很多bug，修了半天也没找到原因大致为以下两个

1. Traceback (most recent call last):
  File "F:\anaconda\envs\pytorch\lib\site-packages\pyglet\__init__.py", line 351, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'get_default'

2.    _default_time_function = time.clock
AttributeError: module 'time' has no attribute 'clock'
实在是有点修不动了，希望作者能够解答

**Comment by The-Alchemist-0517** [comment]
你好，gym的版本是0.20.0, pyglet的版本是1.5.21，我当时gym是用pip指令安装的，并且没有用anaconda建新的虚拟环境。具体运行的过程我在知乎专栏有一两篇文章介绍https://zhuanlan.zhihu.com/p/413937857，https://zhuanlan.zhihu.com/p/417647133，之后的demo运行方式也是类似的。希望对你有帮助。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "The-Alchemist-0517/demo-3.3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月31日(星期一) 晚上11:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[The-Alchemist-0517/demo-3.3] 出现了很多的bug求解 (Issue #1)





 
运行这个代码的gym和pyglet的版本是多少?我是用的在github上下载的一个带rendering的gym，现在的版本都不带rendering了，然后pyglet版本是1.2.4.python是3.7，但是出现很多bug，修了半天也没找到原因大致为以下两个
  
 
Traceback (most recent call last):
 File "F:\anaconda\envs\pytorch\lib\site-packages\pyglet_init_.py", line 351, in getattr
 return getattr(self._module, name)
 AttributeError: 'NoneType' object has no attribute 'get_default'
 
 
 
_default_time_function = time.clock
 AttributeError: module 'time' has no attribute 'clock'
 实在是有点修不动了，希望作者能够解答
